export const DOCUMENTATION_TYPES = [
  "TECHNICAL",
  "BUSINESS",
  "CODE"
];

export const ARCHITECTURES = [
  "MONOLITHIC",
  "MICROSERVICES",
  "EVENT_DRIVEN",
  "PEER_TO_PEER",
  "SOA",
  "SERVERLESS",
  "N_TIER",
  "LAYERED",
  "MVC_MVVM_MVP"
];

export const DATA_ARCHITECTURES = [
  "RELATIONAL_DATABASES",
  "NOSQL",
  "DATA_WAREHOUSES",
  "DATA_LAKES",
  "CACHING",
  "STREAMING_BATCH_PROCESSING"
];

export const DEPLOYMENT_STRATEGIES = [
  "SINGLE_INSTANCE",
  "CLOUD_NATIVE",
  "MULTI_INSTANCE",
  "MULTI_TENANCY",
  "EDGE_COMPUTING",
  "HYBRID_CLOUD"
];

export const USER_EXPERIENCE_AND_FRONT_END = [
  "RESPONSIVE_DESIGN",
  "PROGRESSIVE_WEB_APPS",
  "NATIVE_MOBILE_APPS",
  "CROSS_PLATFORM_DEVELOPMENT"
];

export const SECURITY_AND_AUTHENTICATION = [
  "OAUTH",
  "JWT",
  "SSO",
  "RBAC",
  "MUTUAL_TLS",
  "ENCRYPTION_AT_REST_IN_TRANSIT"
];

export const TECHNOLOGY_STACK = [
  "MEAN",
  "MERN",
  "LAMP",
  "DOT_NET",
  "SPRING_BOOT",
  "DJANGO",
  "FLASK",
  "RUBY_ON_RAILS"
];


